apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-name-deployment
  labels:
    app: call-name-app
spec:
  replicas: 5  # Set the number of replicas to 5
  selector:
    matchLabels:
      app: call-name-app
  template:
    metadata:
      labels:
        app: call-name-app
    spec:
      containers:
      - name: call-name-container
        image: mybanez1/call_name:latest # Use your pushed image
        imagePullPolicy: Always
        stdin: true    # Enable interactive input
        tty: true      # Allocate a terminal session
        ports:
        - containerPort: 80
